name: trigger-build
on: push
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          TRIGGER_URL: ${{ secrets.TriggerUrl }}
        run: curl -X POST -d {} "$TRIGGER_URL"
